# Generated by Django 4.1.5 on 2023-01-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_about_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('complete', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=100),
        ),
    ]
