# Generated by Django 4.1.5 on 2023-01-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('complete', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
