# Generated by Django 4.1.5 on 2023-01-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='about',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('complete', 'Completed'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('NO', 'Normal'), ('SP', 'Split')], default='NO', max_length=2),
        ),
    ]
